INSERT INTO `<DB_PREFIX>vehicles` (`id`, `make`, `model`) VALUES
  (1, 'Albany', 'Alpha'),
  (2, 'Albany', 'Buccaneer'),
  (3, 'Albany', 'Buccaneer Custom'),
  (4, 'Albany', 'Cavalcade'),
  (5, 'Albany', 'Cavalcade FXT'),
  (6, 'Albany', 'Emperor'),
  (7, 'Albany', 'Esperanto'),
  (8, 'Albany', 'Franken Stange'),
  (9, 'Albany', 'Hermes'),
  (10, 'Albany', 'Lurcher'),
  (11, 'Albany', 'Manana'),
  (12, 'Albany', 'Police Roadcruiser'),
  (13, 'Albany', 'Presidente'),
  (14, 'Albany', 'Primo'),
  (15, 'Albany', 'Primo Custom'),
  (16, 'Albany', 'Taxi Cab'),
  (17, 'Albany', 'Romero'),
  (18, 'Albany', 'Roosevelt'),
  (19, 'Albany', 'Roosevelt Valor'),
  (20, 'Albany', 'Stretch'),
  (21, 'Albany', 'Virgo'),
  (22, 'Albany', 'Washington'),
  (23, 'Annis', 'Apocolypse ZR380'),
  (24, 'Annis', 'Elegy RH8'),
  (25, 'Annis', 'Elegy Retro Custom'),
  (26, 'Annis', 'Future Shock ZR380'),
  (27, 'Annis', 'Nightmare ZR380'),
  (28, 'Annis', 'RE-7B'),
  (29, 'Annis', 'Savestra'),
  (30, 'Benefactor', 'Apocalypse Bruiser'),
  (31, 'Benefactor', 'Apocalypse Glendale'),
  (32, 'Benefactor', 'Dubsta'),
  (33, 'Benefactor', 'Dubsta 6x6'),
  (34, 'Benefactor', 'Feltzer'),
  (35, 'Benefactor', 'Future Shock Bruiser'),
  (36, 'Benefactor', 'Future Shock Glendale'),
  (37, 'Benefactor', 'Panto'),
  (38, 'Benefactor', 'Schafter'),
  (39, 'Benefactor', 'Schafter LWB'),
  (40, 'Benefactor', 'Schafter LWB Armored'),
  (41, 'Benefactor', 'Schafter V12'),
  (42, 'Benefactor', 'Schafter V12 Armored'),
  (43, 'Benefactor', 'Glendale'),
  (44, 'Benefactor', 'Nightmare Glendale'),
  (45, 'Benefactor', 'Nightmare Bruiser'),
  (46, 'Benefactor', 'Schlagen GT'),
  (47, 'Benefactor', 'Schwartzer'),
  (48, 'Benefactor', 'Serrano'),
  (49, 'Benefactor', 'Stirling GT'),
  (50, 'Benefactor', 'Strieter'),
  (51, 'Benefactor', 'Surano'),
  (52, 'Benefactor', 'Terrorbyte'),
  (53, 'Benefactor', 'Turreted Limo'),
  (54, 'Benefactor', 'XLS'),
  (55, 'Benefactor', 'XLS Armored'),
  (56, 'BF', 'Bifta'),
  (57, 'BF', 'Dune Buggy'),
  (58, 'BF', 'Dune FAV'),
  (59, 'BF', 'Injection'),
  (60, 'BF', 'Ramp Buggy'),
  (61, 'BF', 'Raptor'),
  (62, 'BF', 'Space Docker'),
  (63, 'BF', 'Surfer'),
  (64, 'Bollokan', 'Prairie'),
  (65, 'Bravado', 'Apocalypse Rat Truck'),
  (66, 'Bravado', 'Apocalypse Sasquatch'),
  (67, 'Bravado', 'Banshee'),
  (68, 'Bravado', 'Banshee 900R'),
  (69, 'Bravado', 'Banshee Topless'),
  (70, 'Bravado', 'Bison'),
  (71, 'Bravado', 'Buffalo'),
  (72, 'Bravado', 'Buffalo S'),
  (73, 'Bravado', 'Duneloader'),
  (74, 'Bravado', 'FIB Buffalo'),
  (75, 'Bravado', 'Future Shock Rat Truck'),
  (76, 'Bravado', 'Future Shock Sasquatch'),
  (77, 'Bravado', 'Gauntlet'),
  (78, 'Bravado', 'Gresley'),
  (79, 'Bravado', 'HalfTrack'),
  (80, 'Bravado', 'Nightmare Rat Truck'),
  (81, 'Bravado', 'Nightmare Sasquatch'),
  (82, 'Bravado', 'Paradise'),
  (83, 'Bravado', 'Police Cruiser Buffalo'),
  (84, 'Bravado', 'RatLoader'),
  (85, 'Bravado', 'RatTruck'),
  (86, 'Bravado', 'Redwood Gauntlet'),
  (87, 'Bravado', 'Rumpo Custom'),
  (88, 'Bravado', 'Rumpo News'),
  (89, 'Bravado', 'Sprunk Buffalo'),
  (90, 'Bravado', 'Verlierer'),
  (91, 'Bravado', 'Youga'),
  (92, 'Bravado', 'Youga Classic'),
  (93, 'Brute', 'Airport Bus'),
  (94, 'Brute', 'Ambulance'),
  (95, 'Brute', 'Armored Boxville'),
  (96, 'Brute', 'Boxville'),
  (97, 'Brute', 'Bus'),
  (98, 'Brute', 'Camper'),
  (99, 'Brute', 'Dashound'),
  (100, 'Brute', 'Police Riot'),
  (101, 'Brute', 'Pony'),
  (102, 'Brute', 'Rental Shuttle Bus'),
  (103, 'Brute', 'Stockade'),
  (104, 'Brute', 'Taco Van'),
  (105, 'Brute', 'Tipper'),
  (106, 'Brute', 'Tipper II'),
  (107, 'Brute', 'Tour Bus'),
  (108, 'Brute', 'Utility Truck'),
  (109, 'Brute', 'Utility Truck Cherry Picker'),
  (110, 'Canis', 'Bodhi'),
  (111, 'Canis', 'Crusader'),
  (112, 'Canis', 'Freecrawler'),
  (113, 'Canis', 'Kalahari'),
  (114, 'Canis', 'Kalahari Topless'),
  (115, 'Canis', 'Kamancho'),
  (116, 'Canis', 'Mesa'),
  (117, 'Canis', 'Seminole'),
  (118, 'Chariot', 'Romero Hearse'),
  (119, 'Cheval', 'Fugitive'),
  (120, 'Cheval', 'Marshall'),
  (121, 'Cheval', 'Picador'),
  (122, 'Cheval', 'Surge'),
  (123, 'Cheval', 'Taipan'),
  (124, 'Coil', 'Brawler'),
  (125, 'Coil', 'Cyclone'),
  (126, 'Coil', 'Raiden'),
  (127, 'Coil', 'Rocket Voltic'),
  (128, 'Coil', 'Voltic'),
  (129, 'Coil', 'Voltic Topless'),
  (130, 'Declasse', 'Apocalypse Brutus'),
  (131, 'Declasse', 'Apocalypse Impaler'),
  (132, 'Declasse', 'Asea'),
  (133, 'Declasse', 'Burger Shot Stallion'),
  (134, 'Declasse', 'Burrito'),
  (135, 'Declasse', 'Drift Tampa'),
  (136, 'Declasse', 'FIB Granger'),
  (137, 'Declasse', 'Future Shock Brutus'),
  (138, 'Declasse', 'Future Shock Impaler'),
  (139, 'Declasse', 'Gang Burrito'),
  (140, 'Declasse', 'Granger'),
  (141, 'Declasse', 'Hotring Sabre'),
  (142, 'Declasse', 'Impaler'),
  (143, 'Declasse', 'Lifeguard'),
  (144, 'Declasse', 'Mamba'),
  (145, 'Declasse', 'Moonbeam'),
  (146, 'Declasse', 'Moonbeam Custom'),
  (147, 'Declasse', 'Nightmare Brutus'),
  (148, 'Declasse', 'Nightmare Impaler'),
  (149, 'Declasse', 'Park Ranger'),
  (150, 'Declasse', 'Police Rancher'),
  (151, 'Declasse', 'Police Transporter'),
  (152, 'Declasse', 'Premier'),
  (153, 'Declasse', 'Rancher XL'),
  (154, 'Declasse', 'Rhapsody'),
  (155, 'Declasse', 'Sabre Turbo'),
  (156, 'Declasse', 'Sabre Turbo Custom'),
  (157, 'Declasse', 'Scramjet'),
  (158, 'Declasse', 'Sheriff Granger'),
  (159, 'Declasse', 'Stallion'),
  (160, 'Declasse', 'Tampa'),
  (161, 'Declasse', 'Tornado'),
  (162, 'Declasse', 'Tornado Convertible'),
  (163, 'Declasse', 'Tornado Custom'),
  (164, 'Declasse', 'Tornado Rat Rod'),
  (165, 'Declasse', 'Tulip'),
  (166, 'Declasse', 'Vamos'),
  (167, 'Declasse', 'Vigero'),
  (168, 'Declasse', 'Voodoo'),
  (169, 'Declasse', 'Voodoo Custom'),
  (170, 'Declasse', 'Weaponized Tampa'),
  (171, 'Declasse', 'Yosemite'),
  (172, 'Dewbauchee', 'Exemplar'),
  (173, 'Dewbauchee', 'JB 700'),
  (174, 'Dewbauchee', 'Massacro'),
  (175, 'Dewbauchee', 'Massacro Racecar'),
  (176, 'Dewbauchee', 'Rapid GT'),
  (177, 'Dewbauchee', 'Rapid GT Classic'),
  (178, 'Dewbauchee', 'Rapid GT Sport'),
  (179, 'Dewbauchee', 'Seven-70'),
  (180, 'Dewbauchee', 'Specter'),
  (181, 'Dewbauchee', 'Specter Custom'),
  (182, 'Dewbuachee', 'Vagner'),
  (183, 'Dinka', 'Akuma'),
  (184, 'Dinka', 'Blista'),
  (185, 'Dinka', 'Blista Compact'),
  (186, 'Dinka', 'Double-T'),
  (187, 'Dinka', 'Enduro'),
  (188, 'Dinka', 'Monkey Blista'),
  (189, 'Dinka', 'Jester'),
  (190, 'Dinka', 'Jester Classic'),
  (191, 'Dinka', 'Jester Racecar'),
  (192, 'Dinka', 'Trust'),
  (193, 'Dinka', 'Vindicator'),
  (194, 'Dundreary', 'Landstalker'),
  (195, 'Dundreary', 'Regina'),
  (196, 'Dundreary', 'Stretch'),
  (197, 'Dundreary', 'Virgo Classic'),
  (198, 'Dundreary', 'Virgo Classic Custom'),
  (199, 'Emperor', 'ETR1'),
  (200, 'Emperor', 'Habanero'),
  (201, 'Enus', 'Cognoscenti'),
  (202, 'Enus', 'Cognoscenti 55'),
  (203, 'Enus', 'Cognoscenti 55 Armored'),
  (204, 'Enus', 'Cognoscenti Armored'),
  (205, 'Enus', 'Cognoscenti Cabrio'),
  (206, 'Enus', 'Huntley S'),
  (207, 'Enus', 'Stafford'),
  (208, 'Enus', 'Super Diamond'),
  (209, 'Enus', 'Windsor'),
  (210, 'Enus', 'Windsor Drop'),
  (211, 'Fathom', 'FQ 2'),
  (212, 'Gallivanter', 'Baller'),
  (213, 'Gallivanter', 'Baller II'),
  (214, 'Gallivanter', 'Baller LE'),
  (215, 'Gallivanter', 'Baller LE Armored'),
  (216, 'Gallivanter', 'Baller LE LWB'),
  (217, 'Gallivanter', 'Baller LE LWB Armored'),
  (218, 'Grotti', 'Bestia GTS'),
  (219, 'Grotti', 'Brioso RA'),
  (220, 'Grotti', 'Carbonizzare'),
  (221, 'Grotti', 'Cheetah'),
  (222, 'Grotti', 'Cheetah Classic'),
  (223, 'Grotti', 'GT500'),
  (224, 'Grotti', 'Itali GTO'),
  (225, 'Grotti', 'Stinger'),
  (226, 'Grotti', 'Stinger GT'),
  (227, 'Grotti', 'Stinger Topless'),
  (228, 'Grotti', 'Turismo Classic'),
  (229, 'Grotti', 'Turismo R'),
  (230, 'Grotti', 'Vigilante'),
  (231, 'Grotti', 'Visione'),
  (232, 'Grotti', 'X80 Proto'),
  (233, 'Hijak', 'Khamelion'),
  (234, 'Hijak', 'Ruston'),
  (235, 'HVY', 'APC'),
  (236, 'HVY', 'Airtug'),
  (237, 'HVY', 'Apocalypse Scarab'),
  (238, 'HVY', 'Barracks'),
  (239, 'HVY', 'Barracks Semi'),
  (240, 'HVY', 'Biff'),
  (241, 'HVY', 'Chernobog'),
  (242, 'HVY', 'Crane'),
  (243, 'HVY', 'Cutter'),
  (244, 'HVY', 'Dock Handler'),
  (245, 'HVY', 'Docktug'),
  (246, 'HVY', 'Dozer'),
  (247, 'HVY', 'Dump'),
  (248, 'HVY', 'Forklift'),
  (249, 'HVY', 'Future Shock Scarab'),
  (250, 'HVY', 'Insurgent'),
  (251, 'HVY', 'Insurgent Pickup'),
  (252, 'HVY', 'Insurgent Pickup Custom'),
  (253, 'HVY', 'Menacer'),
  (254, 'HVY', 'Mixer'),
  (255, 'HVY', 'Mixer II'),
  (256, 'HVY', 'Nightmare Scarab'),
  (257, 'HVY', 'Nightshark'),
  (258, 'HVY', 'Ripley'),
  (259, 'HVY', 'Skylift'),
  (260, 'Imponte', 'Deluxo'),
  (261, 'Imponte', 'Duke O Death'),
  (262, 'Imponte', 'Dukes'),
  (263, 'Imponte', 'Nightshade'),
  (264, 'Imponte', 'Phoenix'),
  (265, 'Imponte', 'Ruiner'),
  (266, 'Imponte', 'Ruiner 2000'),
  (267, 'Invetero', 'Coquette'),
  (268, 'Invetero', 'Coquette BlackFin'),
  (269, 'Invetero', 'Coquette Classic'),
  (270, 'Invetero', 'Coquette Classic Topless'),
  (271, 'Invetero', 'Coquette Topless'),
  (272, 'Jacksheepe', 'Lawn Mower'),
  (273, 'JoBuilt', 'Hauler'),
  (274, 'JoBuilt', 'Hauler Custom'),
  (275, 'JoBuilt', 'Phantom'),
  (276, 'JoBuilt', 'Phantom Custom'),
  (277, 'JoBuilt', 'Phantom Wedge'),
  (278, 'JoBuilt', 'Rubble'),
  (279, 'JoBuilt', 'Trashmaster'),
  (280, 'Karin', '190z'),
  (281, 'Karin', 'Asterope'),
  (282, 'Karin', 'BeeJay XL'),
  (283, 'Karin', 'Dilettante'),
  (284, 'Karin', 'Dilettante Patrol'),
  (285, 'Karin', 'Futo'),
  (286, 'Karin', 'Intruder'),
  (287, 'Karin', 'Kuruma'),
  (288, 'Karin', 'Kuruma Armored'),
  (289, 'Karin', 'Rebel'),
  (290, 'Karin', 'Rusty Rebel'),
  (291, 'Karin', 'Sultan'),
  (292, 'Karin', 'Sultan RS'),
  (293, 'Karin', 'Technical'),
  (294, 'Karin', 'Technical Aqua'),
  (295, 'Karin', 'Technical Custom'),
  (296, 'Lampadati', 'Casco'),
  (297, 'Lampadati', 'Felon'),
  (298, 'Lampadati', 'Felon GT'),
  (299, 'Lampadati', 'Furore GT'),
  (300, 'Lampadati', 'Michelli GT'),
  (301, 'Lampadati', 'Pigalle'),
  (302, 'Lampadati', 'Tropos Rallye'),
  (303, 'Lampadati', 'Viseris'),
  (304, 'LCC', 'Avarus'),
  (305, 'LCC', 'Hexer'),
  (306, 'LCC', 'Innovation'),
  (307, 'LCC', 'Manchez'),
  (308, 'Maibatsu', 'Mule'),
  (309, 'Maibatsu', 'Mule Armored'),
  (310, 'Maibatsu', 'Mule Custom'),
  (311, 'Maibatsu', 'Penumbra'),
  (312, 'Maibatsu', 'Sanchez'),
  (313, 'Maibatsu', 'Sanchez Livery'),
  (314, 'Maibatsu', 'Sanctus'),
  (315, 'Mammoth', 'Patriot'),
  (316, 'Mammoth', 'Patriot Stretch'),
  (317, 'Mammoth', 'Thruster Jetpack'),
  (318, 'MTL', 'Brickade'),
  (319, 'MTL', 'Dune'),
  (320, 'MTL', 'Firetruck'),
  (321, 'MTL', 'Flatbed'),
  (322, 'MTL', 'Packer'),
  (323, 'MTL', 'Pounder'),
  (324, 'MTL', 'Pounder Custom'),
  (325, 'MTL', 'Wastelander'),
  (326, 'Nagasaki', 'BF400'),
  (327, 'Nagasaki', 'Blazer'),
  (328, 'Nagasaki', 'Blazer Aqua'),
  (329, 'Nagasaki', 'Blazer Lifegaurd'),
  (330, 'Nagasaki', 'Caddy'),
  (331, 'Nagasaki', 'Caddy Bunker'),
  (332, 'Nagasaki', 'Caddy Utility'),
  (333, 'Nagasaki', 'Carbon RS'),
  (334, 'Nagasaki', 'Chimera'),
  (335, 'Nagasaki', 'Hot Rod Blazer'),
  (336, 'Nagasaki', 'Shotaro'),
  (337, 'Nagasaki', 'Street Blazer'),
  (338, 'Obey', '9F'),
  (339, 'Obey', '9F Cabrio'),
  (340, 'Obey', 'Omnis'),
  (341, 'Obey', 'Rocoto'),
  (342, 'Obey', 'Tailgater'),
  (343, 'Ocelot', 'Ardent'),
  (344, 'Ocelot', 'F620'),
  (345, 'Ocelot', 'Jackal'),
  (346, 'Ocelot', 'Lynx'),
  (347, 'Ocelot', 'Pariah'),
  (348, 'Ocelot', 'Penetrator'),
  (349, 'Ocelot', 'Stromberg'),
  (350, 'Ocelot', 'Swinger'),
  (351, 'Ocelot', 'XA-21'),
  (352, 'Overflod', 'Autarch'),
  (353, 'Overflod', 'Entity XF'),
  (354, 'Overflod', 'Entity XXR'),
  (355, 'Overflod', 'Tyrant'),
  (356, 'Pegassi', 'Bati 801'),
  (357, 'Pegassi', 'Bati 801RR'),
  (358, 'Pegassi', 'Esskey'),
  (359, 'Pegassi', 'FCR 1000'),
  (360, 'Pegassi', 'FCR 1000 Custom'),
  (361, 'Pegassi', 'Faggio'),
  (362, 'Pegassi', 'Faggio Mod'),
  (363, 'Pegassi', 'Faggio Sport'),
  (364, 'Pegassi', 'Infernus'),
  (365, 'Pegassi', 'Infernus Classic'),
  (366, 'Pegassi', 'Monroe'),
  (367, 'Pegassi', 'Oppressor'),
  (368, 'Pegassi', 'Oppressor MK II'),
  (369, 'Pegassi', 'Osiris'),
  (370, 'Pegassi', 'Reaper'),
  (371, 'Pegassi', 'Ruffian'),
  (372, 'Pegassi', 'Tempesta'),
  (373, 'Pegassi', 'Tezeract'),
  (374, 'Pegassi', 'Torero'),
  (375, 'Pegassi', 'Toros'),
  (376, 'Pegassi', 'Vacca'),
  (377, 'Pegassi', 'Vortex'),
  (378, 'Pegassi', 'Zentorno'),
  (379, 'Pfister', '811'),
  (380, 'Pfister', 'Comet'),
  (381, 'Pfister', 'Comet Retro Custom'),
  (382, 'Pfister', 'Comet Safari'),
  (383, 'Pfister', 'Comet SR'),
  (384, 'Pfister', 'Neon'),
  (385, 'Principe', 'Diabolus'),
  (386, 'Principe', 'Diabolus Custom'),
  (387, 'Principe', 'Lectro'),
  (388, 'Principe', 'Nemesis'),
  (389, 'Progen', 'GP1'),
  (390, 'Progen', 'Itali GTB'),
  (391, 'Progen', 'Itali GTB Custom'),
  (392, 'Progen', 'T20'),
  (393, 'Progen', 'Tyrus'),
  (394, 'RC', 'Bandito'),
  (395, 'Rune', 'Cheburek'),
  (396, 'Schyster', 'Deviant'),
  (397, 'Schyster', 'Fusilade'),
  (398, 'Shitzu', 'Defiler'),
  (399, 'Shitzu', 'Hakuchou'),
  (400, 'Shitzu', 'Hakuchou Drag'),
  (401, 'Shitzu', 'PCJ 600'),
  (402, 'Shitzu', 'Vader'),
  (403, 'Stanley', 'Fieldmaster'),
  (404, 'Stanley', 'Tractor'),
  (405, 'Truffade', 'Adder'),
  (406, 'Truffade', 'Nero'),
  (407, 'Truffade', 'Nero Custom'),
  (408, 'Truffade', 'Z Type'),
  (409, 'Ubermacht', 'Oracle'),
  (410, 'Ubermacht', 'Oracle XS'),
  (411, 'Ubermacht', 'Revolter'),
  (412, 'Ubermacht', 'SC1'),
  (413, 'Ubermacht', 'Sentinel'),
  (414, 'Ubermacht', 'Sentinel Classic'),
  (415, 'Ubermacht', 'Sentinel XS'),
  (416, 'Ubermacht', 'Zion'),
  (417, 'Ubermacht', 'Zion Cabrio'),
  (418, 'Vapid', 'Apocalypse Dominator'),
  (419, 'Vapid', 'Apocalypse Imperator'),
  (420, 'Vapid', 'Apocalypse Slamvan'),
  (421, 'Vapid', 'Benson'),
  (422, 'Vapid', 'Blade'),
  (423, 'Vapid', 'Bobcat XL'),
  (424, 'Vapid', 'Bullet'),
  (425, 'Vapid', 'Caracara'),
  (426, 'Vapid', 'Chino'),
  (427, 'Vapid', 'Chino Custom'),
  (428, 'Vapid', 'Clique'),
  (429, 'Vapid', 'Clown Van'),
  (430, 'Vapid', 'Contender'),
  (431, 'Vapid', 'Desert Raid'),
  (432, 'Vapid', 'Dominator'),
  (433, 'Vapid', 'Dominator GTX'),
  (434, 'Vapid', 'Ellie'),
  (435, 'Vapid', 'FMJ'),
  (436, 'Vapid', 'Flash GT'),
  (437, 'Vapid', 'Future Shock Dominator'),
  (438, 'Vapid', 'Future Shock Imperator'),
  (439, 'Vapid', 'Future Shock Slamvan'),
  (440, 'Vapid', 'GB200'),
  (441, 'Vapid', 'Guardian'),
  (442, 'Vapid', 'Hotknife'),
  (443, 'Vapid', 'Hustler'),
  (444, 'Vapid', 'Minivan'),
  (445, 'Vapid', 'Minivan Custom'),
  (446, 'Vapid', 'Nightmare Dominator'),
  (447, 'Vapid', 'Nightmare Imperator'),
  (448, 'Vapid', 'Nightmare Slamvan'),
  (449, 'Vapid', 'Peyote'),
  (450, 'Vapid', 'Pibwasser Dominator'),
  (451, 'Vapid', 'Police Cruiser'),
  (452, 'Vapid', 'Police Interceptor'),
  (453, 'Vapid', 'Police Prison Bus'),
  (454, 'Vapid', 'Radius'),
  (455, 'Vapid', 'Retinue'),
  (456, 'Vapid', 'Riata'),
  (457, 'Vapid', 'Sadler'),
  (458, 'Vapid', 'Sandking SWB'),
  (459, 'Vapid', 'Sandking XL'),
  (460, 'Vapid', 'Scrap Truck'),
  (461, 'Vapid', 'Sheriff Cruiser'),
  (462, 'Vapid', 'Slamvan'),
  (463, 'Vapid', 'Slamvan Custom'),
  (464, 'Vapid', 'Speedo'),
  (465, 'Vapid', 'Speedo Custom'),
  (466, 'Vapid', 'Stanier'),
  (467, 'Vapid', 'Taxi'),
  (468, 'Vapid', 'The Liberator'),
  (469, 'Vapid', 'Tow Truck'),
  (470, 'Vapid', 'Tow Truck Large'),
  (471, 'Vapid', 'Trophy Truck'),
  (472, 'Vapid', 'Unmarked Cruiser'),
  (473, 'Vapid', 'Utility Truck'),
  (474, 'Vulcar', 'Fagaloa'),
  (475, 'Vulcar', 'Ingot'),
  (476, 'Vulcar', 'Warrener'),
  (477, 'Weeny', 'Apocalypse Issi'),
  (478, 'Weeny', 'Future Shock Issi'),
  (479, 'Weeny', 'Issi'),
  (480, 'Weeny', 'Issi Classic'),
  (481, 'Weeny', 'Nightmare Issi'),
  (482, 'Western Motorcycle Company', 'Bagger'),
  (483, 'Western Motorcycle Company', 'Cliffhanger'),
  (484, 'Western Motorcycle Company', 'Daemon'),
  (485, 'Western Motorcycle Company', 'Daemon Custom' ),
  (486, 'Western Motorcycle Company', 'Gargoyle'),
  (487, 'Western Motorcycle Company', 'Nightblade'),
  (488, 'Western Motorcycle Company', 'Police Bike'),
  (489, 'Western Motorcycle Company', 'Rat Bike'),
  (490, 'Western Motorcycle Company', 'Sovereign'),
  (491, 'Western Motorcycle Company', 'Wolfsbane'),
  (492, 'Western Motorcycle Company', 'Zombie Bobber'),
  (493, 'Western Motorcycle Company', 'Zombie Chopper'),
  (494, 'Willard', 'Faction'),
  (495, 'Willard', 'Faction Custom'),
  (496, 'Willard', 'Faction Custom Donk'),
  (497, 'Zirconium', 'Journey'),
  (498, 'Zirconium', 'Stratum'),
  (499, 'Benefactor', 'BR8'),
  (500, 'BF', 'Club'),
  (501, 'Canis', 'Seminole Frontier'),
  (502, 'Declasse', 'DR1'),
  (503, 'Dundreary', 'Landstalker XL'),
  (504, 'Bravado', 'Gauntlet Classic Custom'),
  (505, 'Benefactor', 'Glendale Custom'),
  (506, 'Imponte', 'Beater Dukes'),
  (507, 'Invetero', 'Coquette D10'),
  (508, 'Lampadati', 'Tigon'),
  (509, 'Maibatsu', 'Penumbra FF'),
  (510, 'Albany', 'Manana Custom'),
  (511, 'Vapid', 'Peyote Custom'),
  (512, 'Yosemite', 'Rancher'),
  (513, 'Youga', 'Classic 4x4') ,
  (515, 'Maxwll', 'Asbo'),
  (516, 'Lampadati', 'Komoda'),
  (517, 'Karen', 'Everon'),
  (518, 'Ubermacht', 'Rebla GTS'),
  (519, 'Vapid', 'Retinue Mk II'),
  (520, 'Maxwell', 'Vagrant'),
  (521, 'Obey', 'BF Drafter'),
  (522, 'Vapid', 'Caracara 4x4'),
  (523, 'Weeny', 'Dynasty'),
  (524, 'Progen', 'Emerus'),
  (525, 'Bravado', 'Gauntlet Classic'),
  (526, 'Bravado', 'Gauntlet Hellfire'),
  (527, 'Annis', 'Hellion'),
  (528, 'Weeny', 'Issy Sport'),
  (529, 'Ocelot', 'Jugular'),
  (530, 'Benefactor', 'Krieger'),
  (531, 'Ocelot', 'Locust'),
  (532, 'Vulcar', 'Nebula Turbo'),
  (533, 'Vysser', 'Neo'),
  (534, 'Lampadati', 'Novak'),
  (535, 'Enus', 'Paragon R'),
  (536, 'Enus', 'Paragon R (Armored)'),
  (537, 'Vapid', 'Peyote Gasser'),
  (538, 'Western', 'Rampant Rocket Tricycle'),
  (539, 'Annis', 'S800R'),
  (540, 'Truffade', 'Thrax'),
  (541, 'Ubermact', 'Zion Classic'),
  (542, 'Pegassi', 'Zorrusso'),
  (543, 'Nagasaki', 'Stryder'),
  (544, 'Progen', 'PR4'),
  (545, 'Ocelot', 'R88'),
  (546, 'Dinka', 'Blista Kanjo'),
  (547, 'Dinka', 'Sungoi'),
  (548, 'Declasse', 'Drift Yosemite'),
  (549, 'Nagasaki', 'Outlaw'),
  (550, 'Karen', 'Sultan Classic'),
  (551, 'Overflod', 'Imorgon'),
  (552, 'Rune', 'Zhaba'),
  (553, 'Dewbauchee', 'JB 700W'),
  (554, 'Grotti', 'Furia');
